name: _dummy_flutter_pkg
environment:
  sdk: '^3.5.0'
  flutter: '>=1.0.0'
dependencies:
  camera: ^0.11.0+2
dev_dependencies:
  test:
version: 0.0.4
description: 'Dummy package used to validate publication flow'
repository: https://github.com/sigurdm/private_repository2