name: _dummy_flutter_pkg
environment:
  sdk: '^3.5.0'
  flutter: '>=1.0.0'
dependencies:
  camera:
dev_dependencies:
  test:
version: 0.0.3
description: 'Dummy package used to validate publication flow'
