name: CI
on:
  push: {branches: [master]}
  pull_request:

jobs:
  test:
    name: "Tests | Dart ${{ matrix.dart-channel }} | ${{ matrix.os }}"

    strategy:
      matrix:
        os: [ubuntu, windows]
        dart-channel: [stable]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.dart-channel }}
    - run: dart --version

    - run: dart pub get
    - run: dart pub run test -r expanded
